name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: first steps
        run: echo "first step from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
        
      - name: context variables
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job context: $JOB_CONTEXT"
          echo "Done!"
